# Generated by Django 3.2.5 on 2022-06-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('target', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('pharmacy_expiries', models.FloatField()),
                ('lab_expiries', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expiry',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('lab_target', models.FloatField()),
                ('pharma_target', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MonthlyTargets',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('sales', models.FloatField()),
                ('lab_contribution', models.FloatField()),
                ('pharmacy_contribution', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('end_month_stock', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'EndOfMonthStock',
            },
        ),
        migrations.CreateModel(
            name='Twinkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('amount_to_twinkle', models.FloatField()),
                ('amount_to_metropolis_diamond', models.FloatField()),
                ('amount_for_twinkle', models.FloatField()),
                ('commission', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('weekly_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Twinkle',
            },
        ),
        migrations.CreateModel(
            name='WeeklyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_received', models.FloatField()),
                ('amount_referred', models.FloatField()),
                ('balance', models.FloatField()),
                ('weekly_last_updated', models.DateTimeField(auto_now=True)),
                ('weekly_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'WeeklyData',
            },
        ),
        migrations.CreateModel(
            name='SummaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=6, max_length=9)),
                ('sales', models.FloatField()),
                ('cost_of_sales', models.FloatField()),
                ('gross_profit', models.FloatField()),
                ('expense', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sales_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales')),
            ],
            options={
                'verbose_name_plural': 'Summary',
            },
        ),
    ]
