# Generated by Django 3.2.5 on 2022-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=9)),
                ('sales', models.IntegerField()),
                ('lab_contribution', models.IntegerField()),
                ('pharmacy_contribution', models.IntegerField()),
            ],
        ),
    ]
