# Generated by Django 3.2.5 on 2022-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220417_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('weekly_sales', models.IntegerField()),
                ('weekly_lab_contribution', models.IntegerField()),
                ('weekly_pharmacy_contribution', models.IntegerField()),
                ('weekly_last_updated', models.DateTimeField(auto_now=True)),
                ('weekly_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
