# Generated by Django 3.2.5 on 2022-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_weeklydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='lab_contribution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pharmacy_contribution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='weekly_lab_contribution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='weekly_pharmacy_contribution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklydata',
            name='weekly_sales',
            field=models.FloatField(),
        ),
    ]
