# Generated by Django 3.2.5 on 2022-04-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220417_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklydata',
            old_name='weekly_lab_contribution',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='weeklydata',
            old_name='weekly_pharmacy_contribution',
            new_name='amount_referred',
        ),
        migrations.RenameField(
            model_name='weeklydata',
            old_name='weekly_sales',
            new_name='balance',
        ),
    ]
