# Generated by Django 3.2.5 on 2022-04-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220417_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twinkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=4, max_length=9)),
                ('amount_to_twinkle', models.FloatField()),
                ('amount_to_metropolis_diamond', models.FloatField()),
                ('amount_for_twinkle', models.FloatField()),
                ('commission', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('weekly_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
