# Generated by Django 3.2.5 on 2022-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_twinkle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022, null=True)),
                ('target', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('weekly_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
